CREATE DATABASE IF NOT EXISTS osu DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_store DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_mp DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_chat DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_charts DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_updates DEFAULT CHARSET utf8mb4;

CREATE DATABASE IF NOT EXISTS osu_test DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_store_test DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_mp_test DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_chat_test DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_charts_test DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS osu_updates_test DEFAULT CHARSET utf8mb4;
