#!/bin/sh

set -u
set -e

cd "$(dirname "${0}")/../.."

test -f .env || cp .env.example .env
./build.sh

# undo config caching by the script above
php artisan config:clear

php-fpm7 -y "$PWD/docker/php/php-fpm.conf"
