preset: laravel

enabled:
  - strict
  - strict_param
  - unalign_double_arrow

disabled:
  - logical_not_operators_with_successor_space
  - phpdoc_summary

finder:
  not-path:
    - resources/lang/be
    - resources/lang/bg
    - resources/lang/cs
    - resources/lang/da
    - resources/lang/de
    - resources/lang/el
    - resources/lang/es
    - resources/lang/fi
    - resources/lang/fr
    - resources/lang/hu
    - resources/lang/id
    - resources/lang/it
    - resources/lang/ja
    - resources/lang/ko
    - resources/lang/nl
    - resources/lang/no
    - resources/lang/pl
    - resources/lang/pt
    - resources/lang/pt-br
    - resources/lang/ro
    - resources/lang/ru
    - resources/lang/sk
    - resources/lang/sv
    - resources/lang/th
    - resources/lang/tr
    - resources/lang/vi
    - resources/lang/zh
    - resources/lang/zh-tw
