apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-shared
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.laravel.debug }}
  appDebug: "true"
  {{- end }}
  appEnv: {{ required "Missing app env" .Values.config.laravel.env }}
  {{- if .Values.config.db.database }}
  dbDatabase: {{ .Values.config.db.database }}
  {{- end }}
  dbHost: {{ required "Missing db host" .Values.config.db.host }}
  {{- if .Values.config.db.password }}
  dbPassword: {{ .Values.config.db.password }}
  {{- end }}
  {{- if .Values.config.db.port }}
  dbPort: {{ .Values.config.db.port }}
  {{- end }}
  {{- if .Values.config.db.user }}
  dbUser: {{ .Values.config.db.user }}
  {{- end }}
  {{- if .Values.config.dbName.chat }}
  dbNameChat: {{ .Values.config.dbName.chat }}
  {{- end }}
  laravelAppKey: "{{ required "Missing Laravel appKey" .Values.config.laravel.appKey }}"
  laravelOauthPublicKey: {{- printf " |%s" (required "Missing Laravel oauthPublicKey" .Values.config.laravel.oauth.publicKey | nindent 4) }}
  laravelOauthPrivateKey: {{- printf " |%s" (required "Missing Laravel oauthPrivateKey" .Values.config.laravel.oauth.privateKey | nindent 4) }}
  redisAppHost: {{ required "Missing redis host" .Values.config.redis.app.host }}
  {{- if .Values.config.redis.app.port }}
  redisAppPort: "{{ .Values.config.redis.app.port }}"
  {{- end }}
  redisNotificationHost: {{ required "Missing redis notification host" .Values.config.redis.notification.host }}
  {{- if .Values.config.redis.notification.port }}
  redisNotificationPort: "{{ .Values.config.redis.notification.port }}"
  {{- end }}
