#import Schema/*.gql

scalar DateTimeTz @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTimeTz")

type Query {
    changelog(
        id: Int @eq(key: "changelog_id"),
        build: String @eq(key: "build"),
        stream: String @eq(key: "stream_id")
    ): Changelog @first
    changelogs: [Changelog!]! @paginate(type: CONNECTION)

    newsPost(
        id: Int @eq,
        slug: String @eq
    ): NewsPost @first
    news: [NewsPost!]! @paginate(type: CONNECTION)
}

extend type Query @oauth {
    "Get an osu beatmap"
    beatmap(
        id: Int @eq(key: "beatmap_id")
        checksum: String
        filename: String
    ): Beatmap @first
    beatmaps(
        includeIDs: [Int!]! @in(key: "beatmap_id")
    ): [Beatmap!]! @all

    beatmapsets(
        includeIDs: [Int!] @in(key: "beatmapset_id")
        orderBy: _ @orderBy(columns: [
            "title",
            "artist"
        ])
    ): [Beatmapset!]! @paginate(type: CONNECTION)

    group(
        id: Int @eq(key: "group_id")
    ): Group @first
    groups: [Group!]! @paginate(type: CONNECTION)

    "Get an osu user"
    user(
        id: Int @eq(key: "user_id")
        username: String @eq
    ): User @first

    "Gets the currently authenticated user"
    me: User
        @restrict(scopes: ["identify"])
        @auth
}
