# -*- mode: ruby -*-
# vi: set ft=ruby :

# provision script for the vm
provision_script = <<SCRIPT

# Required to add php 7 repository
# https://launchpad.net/~ondrej/+archive/ubuntu/php
export LANG=en_US.UTF-8

echo I am provisioning...
cd /data/osu\!web/

echo Setting up php, nginx, mysql
./bootstrap.sh

echo Bind mounting node_modules
echo "/data/node_modules $PWD/node_modules none bind,noauto 0 0" >> /etc/fstab
mkdir -p /data/node_modules "$PWD/node_modules"
mount "$PWD/node_modules"
chown vagrant "$PWD/node_modules"

echo setup osu!web stuff
mysql -u root < vagrant/mysql_user.sql
cp .env.example .env
sudo -H -u vagrant ./build.sh
./bin/db_seed

date > /etc/vagrant_provisioned_at
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty32"

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8000, host: 8081
  config.vm.network :forwarded_port, guest: 3306, host: 3366

  config.vm.synced_folder "../", "/data/osu!web", :mount_options => ["dmode=777,fmode=777"]

  config.vm.provider :virtualbox do |vb|
    vb.name = "osu!web"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--ostype", "Ubuntu"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
  end

  config.vm.provider :docker do |d, override|
    override.vm.box = nil
    d.name = "osu-web"
    d.has_ssh = true
    d.build_dir = "."
    d.build_args = ["-t", "osu-web"]
    d.create_args = ["--privileged"]
  end

  config.vm.provision "shell", inline: provision_script
  config.vm.provision "shell", inline: "mount /data/osu!web/node_modules",
    run: "always"
  config.vm.provision "shell", inline: "sudo service nginx restart",
    run: "always"
end
