enum Playmode {
    osu
    taiko
    mania
    catch
}

enum ProfileElement {
    me
    medals
    beatmaps
    kudosu
    recent_activity
    top_ranks
    historical
}

enum Playstyle {
    keyboard
    tablet
    mouse
    touch
}

enum BeatmapStates {
    graveyard @enum(value: -2)
    wip       @enum(value: -1)
    pending   @enum(value:  0)
    ranked    @enum(value:  1)
    approved  @enum(value:  2)
    qualified @enum(value:  3)
    loved     @enum(value:  4)
}
